{% set name = "deprecated" %}
{% set version = "1.2.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 422b6f6d859da6f2ef57857761bfb392480502a64c3028ca9bbe86085d72115d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<27]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - wrapt >=1.10,<2
  run:
    - python
    - wrapt >=1.10,<2

test:
  source_files:
    - tests
  imports:
    - deprecated
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/laurent-laporte-pro/deprecated
  summary: Python @deprecated decorator to deprecate old python classes, functions or methods.
  license: MIT
  license_file: LICENSE.rst
  license_family: MIT
  description: |
    If you need to mark a function or a method as deprecated, you can use the @deprecated decorator
  dev_url: https://github.com/laurent-laporte-pro/deprecated
  doc_url: https://readthedocs.org/projects/deprecated

extra:
  recipe-maintainers:
    - mariusvniekerk
