{% set name = "Deprecated" %}
{% set version = "1.2.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 422b6f6d859da6f2ef57857761bfb392480502a64c3028ca9bbe86085d72115d
  skip: True  # [py<27]

build:
  number: 0
  script: {{ PYTHON }} -m pip install --ignore-installed --no-deps --no-build-isolation . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - wrapt >=1.10,<2
  run:
    - python
    - wrapt >=1.10,<2

test:
  imports:
    - deprecated
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - setuptools  # [py>=312]
  commands:
    - pip check
    - pytest -v

about:
  home: https://github.com/laurent-laporte-pro/deprecated
  license: MIT
  license_file: LICENSE.rst
  license_family: MIT
  summary: Python @deprecated decorator to deprecate old python classes, functions or methods.
  dev_url: https://github.com/laurent-laporte-pro/deprecated
  doc_url: https://github.com/laurent-laporte-pro/deprecated

extra:
  recipe-maintainers:
    - mariusvniekerk
