{% set name = "Deprecated" %}
{% set version = "1.2.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/D/Deprecated/deprecated-1.2.18.tar.gz
  sha256: 422b6f6d859da6f2ef57857761bfb392480502a64c3028ca9bbe86085d72115d
  skip: true  # [py<27]

build:
  number: 0
  script: {{ PYTHON }} -m pip install --ignore-installed --no-deps .
  skip: true  # [py==30,==31,==32,==33]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - wrapt >=1.10,<2
  run:
    - python
    - wrapt <2,>=1.10

test:
  imports:
    - deprecated

about:
  home: https://github.com/tantale/deprecated
  license: MIT
  license_file: LICENSE.rst
  license_family: MIT
  # https://github.com/tantale/deprecated/pull/1
  # license_file: ''
  summary: Python @deprecated decorator to deprecate old python classes, functions or methods.
  dev_url: https://github.com/tantale/deprecated

extra:
  recipe-maintainers:
    - mariusvniekerk
