{% set name = "Deprecated" %}
{% set version = "1.2.3" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "0b1e043af3bab6c7ebcf96a471d0e75685ffe1390924e28137a8f1bd33781195" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  noarch: python
  script: python -m pip install --ignore-installed --no-deps .

requirements:
  host:
    - python
    - pip
    - wrapt <2,>=1
  run:
    - python
    - wrapt <2,>=1

test:
  imports:
    - deprecated

about:
  home: https://github.com/tantale/deprecated
  license: MIT
  license_family: MIT
  # https://github.com/tantale/deprecated/pull/1
  # license_file: ''
  summary: Python @deprecated decorator to deprecate old python classes, functions or methods.
  dev_url: 'https://github.com/tantale/deprecated'

extra:
  recipe-maintainers:
   - mariusvniekerk
