travis:
  secure:
    BINSTAR_TOKEN: ewJmnaafNFG9Rwvdx0ESnWufK4K/wQNwjrKxUwWRZEtIO50aIgq+SApRWBbuJkY53osAFUBu6w+KokppGEjjjqoB23vhEnRBtJaalXk76CkLPPtIV/g+UMT5nIAE+DGDXTi090PA8Et4kjYOe2nrRN6pSdqDICh2HQ9kppR+wOF65FJGp7nUNxC5b3rIlicMNvtwg2juHIhaQzXe7qo/1s1SEhR/dmmUZ2w3SojMJp8oDJ/S9K6DDs+B/qZOR62Rwg3G8wvd1Ua/xU8cn9WeJxWXTa9MamSiAIW9anLX6mZ1dAVfEWMkg356iPbQoLN0aHslBS+Jkxo+UXGvy4kf8AfwTyxUfUkj5Wx6D8vth7ZZVHG3jBk85reHh2U3ulwnlQMZwLk9fl3N/Y6HMGwaMYtOIT7g5c+o+9/zLSYvls17XqN2KquO0WYrrps6I4mJKUY6IQfpAnq747PuqVfwXjJU/qDemMmAvry+Jg3nBNFAczztnfEidxA6QztMAIOzCLP5iH3domRH1qBWfAMskNniyCq6tpyqYp7agAhWZTtig5Mzw3Ie1QEaaap4226HSHj1FVWzlci82ltCecBdsXUYmbImLaze/Ge04t+nPHZgLi3DWi8IuNMPV+zpmpI/kzZU8+2yAd1PhVyEFuRyR7lTs21M7D6gX2MafHkdqBI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
