travis:
  secure:
    BINSTAR_TOKEN: D6s5+abU/QGl2D1cBf9zSUHtuDk0Tti1na91GElZbd9ZnUi5PSEbbYQZp2vsYg+eR8yMg3yJEJWLB9TTUvA3AqKWo4LXh/19Txr7xuUJOMuwjm2yvDY6ShUfvMYsqlC+XF4lecODhy55p8hQeN6m94M6++CiIi8Iy9sWlQLolshOjtYIxzRZ3PgUXtL30xtIYKqnIA3hOM6G/mmqIWHQ6XwSubbJPf30LTIE4OPzpw0ZmlvlGp8G1zzm9Kq3udEPggADYGbpeZPETG5yjYBz1EKa0Y56RqE3NflVMB76/hAMJ+NpvBII6WIWuCDXPVnpzKSjpura4lhsJ1RFNpcJHfe9Y1I48Mrd6p3PpsWvt1Eo2bqVoIaDiqpNRcdsjy44LARBoX03oV8mfLjam8Wbkj1cN7q14Wfv110yXt0qVo1I4NNWG0UeKT3dL3YiBdaFcyNt4lblZSek5A1S4KI4PgSe1eFufQ7utAjP/jHcxaBw1kwaFN29PSfLrJ750HFnAZ5tfwAQReGgcEt2GTW9AZH0tnZbagmLfkpadktfee72GGwoF+8daAdoqADvvZ87PIFrnr/5r/Bp/yN1Gabor/Z94WNxTKLW25zlwJkfkg/3B4PbREU5o8WxPdwsu1xH2JYaI8USIq2MunQpW9hGB1587t13X9whk5DTMDzQnSg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
